CREATE TABLE person (
    PERSON_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    AGE INTEGER NOT NULL UNIQUE,
    IS_COOL INTEGER NOT NULL,
    CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TEXT DEFAULT NULL,
    UNIQUE(NAME, AGE)
);